print(2+4)
print("shivam")
print ('c:\docs\Tripathi')
print(8//9)
print(3**2)
print(90/10)
print("shivam"+"mani")
print("shivam's coder")
print('Shivam "geekcoder"')
print('shivam\'s"Don"')
print ('c:\docs\nripathi')
print ('c:\docs\tripathi')
print (r'c:\docs\tripathi')
print (2-10)
print (3*'shivam')
name='Geekcodershivam'
print (name)
print (name[2:])
print (name[0:3])
print (name[:8])
print (name[-1])
print (name[0:0])
print (name[1:9])
print (name[:10])

